"""Browser interface for exchange-wide search and traceable analysis."""

def section():
    return r'''<section><h2>섹터 검색 · 거래소 전체 목록</h2>
<p class="na">거래소 목록을 갱신한 뒤 검색하세요. 전체 상장 목록과 테마 분류 범위는 별도입니다. 미분류 종목은 섹터 검색에서 누락될 수 있습니다.</p>
<form id="sector-form"><input id="sector-query" placeholder="AI, 반도체, 전력, 종목명" maxlength="100" aria-label="섹터 검색">
<select id="sector-market" aria-label="시장"><option value="">전체 국가</option><option value="KR">한국</option><option value="US">미국</option><option value="SG">싱가포르</option></select>
<button>검색</button><button type="button" id="catalog-refresh">선택 국가 목록 갱신</button></form>
<p id="catalog-health" class="na"></p><p id="search-state" role="status"></p>
<button type="button" id="evaluate-selected">선택 종목 평가</button> <button type="button" id="evaluate-all">검색 결과 전체 평가</button>
<button type="button" id="enrich-all">검색 결과 전체 관찰 자료 수집</button>
<button type="button" id="enrich-selected">선택 종목 관찰·ETF 자료 수집</button>
<button type="button" id="cancel-search-job" disabled>평가 취소</button>
<p id="search-job-state" role="status"></p><div id="search-results" class="scroll"></div>
<button type="button" id="search-prev">이전</button><button type="button" id="search-next">다음</button>
<div id="search-analysis"></div><h3>주도주 관찰 후보 · ETF·기관 데이터</h3>
<h4>다음 유망 섹터를 찾는 여섯 가지 신호</h4>
<p class="na">산업의 호황과 주가 상승은 시점이 다를 수 있습니다. 여러 신호가 함께 개선되는지 확인하고, 현재 주가에 기대가 얼마나 반영됐는지도 살펴보세요.</p>
<div class="scroll"><table aria-label="유망 섹터 관찰 신호"><thead><tr><th>확인할 신호</th><th>구체적으로 볼 것</th><th>현재 확인 방법</th></tr></thead><tbody>
<tr><td><strong>수요 회복</strong></td><td>신규 수주·판매량 증가, 재고 감소, 제품 가격 상승</td><td>공시·사업보고서 추가 확인 · 자동 추적 미구현</td></tr>
<tr><td><strong>이익 개선</strong></td><td>매출뿐 아니라 영업이익률·현금흐름도 개선되는지</td><td>관찰 자료 수집 후 종목별 연간 실적 변화 확인</td></tr>
<tr><td><strong>예상 실적 상향</strong></td><td>향후 이익 전망을 올리는 기업이 섹터 안에서 늘어나는지</td><td>기업 전망·실적 예상 자료 추가 확인 · 자동 추적 미구현</td></tr>
<tr><td><strong>시장 대비 강세</strong></td><td>최근 3·6개월 수익률이 시장보다 높은지</td><td>종목 상세의 3·6개월 상대강도 확인 · 비교 ETF 기준</td></tr>
<tr><td><strong>상승의 확산</strong></td><td>대표 종목 한두 개 외에 여러 관련 기업이 함께 오르는지</td><td>같은 섹터의 여러 종목 관찰 자료 비교 · 미수집 종목은 판단 제외</td></tr>
<tr><td><strong>가격 부담</strong></td><td>좋아질 실적을 현재 주가가 이미 과도하게 반영했는지</td><td>가치평가의 보수적·기준·낙관적 가치와 안전마진 확인 · 미래 실적 가정 별도 검토</td></tr>
</tbody></table></div>

<p class="na">종목의 상세 버튼에서 평가·관찰 지표·ETF·기관 자료를 확인합니다. 미수집 신호는 점수로 채우지 않습니다. 미국 기관 정보는 분기 보유 변화입니다.</p><div id="search-detail"></div>
<details><summary>기관 공시·자료 연결</summary><label>미국 기관 CIK <input id="manager-cik" placeholder="기관 식별번호" maxlength="10"></label><button type="button" id="manager-refresh">미국 분기 보유 공시 수집</button><p class="na">SEC 연락처 설정이 필요합니다. 확인된 CUSIP 매핑이 없는 종목은 자동 연결하지 않습니다.</p>
<label>출처가 포함된 목록·ETF·기관 JSON 자료 <input id="data-import" type="file" accept="application/json,.json"></label><button type="button" id="import-data">자료 불러오기</button><p class="na">자동 연결되지 않은 시장은 출처·기준일·종목 식별자가 있는 자료를 불러올 수 있습니다.</p></details>
</section>
<script>
(()=>{let offset=0,total=0,job=null,timer=null;const chosen=new Set();const $=id=>document.getElementById(id);
const text=(id,value)=>$(id).textContent=value;
async function request(url,options){const r=await fetch(url,options);const j=await r.json();if(!r.ok)throw Error(typeof j.detail==='string'?j.detail:'요청을 확인하세요');return j}
function params(){return {query:$('sector-query').value,market:$('sector-market').value}}
function cell(tr,value){const td=document.createElement('td');td.textContent=value==null?'–':String(value);tr.append(td);return td}
async function showDetail(id){try{const d=await request('api/discovery/detail?listing_id='+encodeURIComponent(id));const box=$('search-detail');box.replaceChildren();const h=document.createElement('h3');h.textContent=d.listing.name+' · '+d.listing.ticker;box.append(h);const t=document.createElement('table');function field(k,v){const tr=document.createElement('tr');cell(tr,k);cell(tr,v);t.append(tr)}const a=d.valuation||{},v=a.valuation||{},l=d.leadership||{};field('분석일',d.analysis_day);field('종합 점수',a.total);field('가치평가 점수 /35',a.parts?.valuation);field('주도주 관찰 점수',l.score);field('관찰 보류 사유',(l.missing||[]).join(', '));field('관찰 자료 기준일',l.as_of);field('관찰 출처',l.source);field('상대강도 3/6/12개월',[l.signals?.rs_3m,l.signals?.rs_6m,l.signals?.rs_12m].map(x=>x==null?'–':x.toFixed(1)+'%').join(' / '));for(const [k,r]of Object.entries(v.scenarios||{})){field(({base:'기준',conservative:'보수적',optimistic:'낙관적'}[k]||k)+' 가치',r.value+' '+(v.currency||''));field('안전마진',r.safety_margin==null?'–':r.safety_margin.toFixed(1)+'%')}field('평가 보류·검토',(a.avoid||v.missing||[]).join(', '));for(const r of d.institution_changes||[]){field('기관 · 기준 분기',r.manager+' · '+r.quarter);field('보유 주식 수 변화',r.shares_change);field('보유 가치 변화',r.value_change+' '+r.currency)}for(const f of d.flows||[]){if(f.kind==='leadership')continue;const r=f.data;field('자료 종류 · 기준일',f.kind+' · '+f.period);field('출처',r.source);if(r.nav!=null)field('ETF NAV',r.nav+' '+r.currency);if(r.aum!=null)field('ETF 규모',r.aum);if(r.creation_estimate)field('설정/환매 추정',r.creation_estimate.flow??'자료 조건 부족');if(r.net_creation!=null)field('공식 설정/환매',r.net_creation+' '+r.currency);if(r.holdings)field('ETF 구성 종목',r.holdings.map(x=>x.ticker+' '+(100*x.weight).toFixed(2)+'%').join(', '));if(r.manager)field('기관 분기 보유',r.manager+' · '+r.shares+'주');if(r.rows)for(const day of r.rows)field('기관·투자자 순매수 '+day.date,Object.entries(day.investors).map(([k,v])=>k+': '+v.toLocaleString()+'원').join(' / '))}if(!(d.flows||[]).some(f=>f.kind!=='leadership'))field('ETF·기관','미수집 또는 미지원');box.append(t);if(d.listing.market==='KR'){const b=document.createElement('button');b.textContent='최근 30일 기관 순매수 수집';b.onclick=async()=>{const end=new Date(),start=new Date(end);start.setDate(start.getDate()-30);text('search-job-state','기관 자료 수집 중');const q=new URLSearchParams({listing_id:id,start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)});try{const r=await request('api/discovery/institution/refresh?'+q,{method:'POST'});text('search-job-state',r.note||'기관 자료 수집 완료');showDetail(id)}catch(e){text('search-job-state',e.message)}};box.append(b)}}catch(e){text('search-detail',e.message)}}
async function find(){try{const p=params(),qs=new URLSearchParams({query:p.query,offset,limit:50});if(p.market)qs.set('market',p.market);const r=await request('api/discovery/search?'+qs);total=r.total;text('search-state','검색 결과 '+r.total+'개 · 전체 목록 '+r.total_listings+'개 · 분류 근거 확보 '+r.classified+'개');const t=document.createElement('table'),head=document.createElement('tr');for(const v of ['선택','국가','종목','유형','분류 근거','상세']){const th=document.createElement('th');th.textContent=v;head.append(th)}t.append(head);for(const x of r.items){const tr=document.createElement('tr'),td=cell(tr,'');const c=document.createElement('input');c.type='checkbox';c.checked=chosen.has(x.id);c.setAttribute('aria-label',x.name+' 선택');c.onchange=()=>c.checked?chosen.add(x.id):chosen.delete(x.id);td.append(c);cell(tr,x.market);cell(tr,x.ticker+' '+x.name);cell(tr,x.type);cell(tr,x.evidence.map(e=>e.label+' ('+e.source+')').join(' / ')||'미분류');const b=document.createElement('button');b.textContent='상세';b.onclick=()=>showDetail(x.id);cell(tr,'').append(b);t.append(tr)}$('search-results').replaceChildren(t);$('search-prev').disabled=offset===0;$('search-next').disabled=offset+50>=total}catch(e){text('search-state',e.message)}}
async function health(){try{const h=await request('api/discovery/sources');text('catalog-health',Object.entries(h).map(([m,s])=>m+': '+({captured:'수집 완료',not_collected:'미수집',connection_unavailable:'연결 확인 필요',imported:'파일 자료'}[s.status]||s.status)+(s.listings?' '+s.listings+'개':'')).join(' · '))}catch(e){text('catalog-health',e.message)}}
async function poll(){if(!job)return;try{const j=await request('api/discovery/jobs/'+job);text('search-job-state',j.state+' · 처리 '+(j.completed+j.failed)+'/'+j.total+' · 실패 '+j.failed);const box=$('search-analysis');box.replaceChildren();for(const r of j.results){const p=document.createElement('p');const a=r.analysis||{},v=a.valuation||{},s=v.scenarios?.base||v.scenarios?.['기준'];p.textContent=r.ticker+' · '+(a.analysis_status||r.status)+' · 총점 '+(a.total??'–')+' · 가치평가 '+(a.parts?.valuation??'–')+'/35'+(s?' · 안전마진 '+s.safety_margin+'%':'');box.append(p)}if(['completed','cancelled','error','interrupted'].includes(j.state)){clearInterval(timer);timer=null;$('cancel-search-job').disabled=true}}catch(e){text('search-job-state',e.message)}}
async function evaluate(all){try{const p=params();const body=all?{query:p.query,market:p.market||null}:{listing_ids:[...chosen]};const j=await request('api/discovery/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});job=j.id;localStorage.setItem('sector-job',job);$('cancel-search-job').disabled=false;if(timer)clearInterval(timer);timer=setInterval(poll,3000);poll()}catch(e){text('search-job-state',e.message)}}
$('sector-form').onsubmit=e=>{e.preventDefault();offset=0;chosen.clear();find()};$('search-prev').onclick=()=>{offset=Math.max(0,offset-50);find()};$('search-next').onclick=()=>{offset+=50;find()};$('enrich-all').onclick=async()=>{try{const p=params(),r=await request('api/discovery/enrich',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:p.query,market:p.market||null})});job=r.id;localStorage.setItem('sector-job',job);$('cancel-search-job').disabled=false;if(timer)clearInterval(timer);timer=setInterval(poll,3000);poll()}catch(e){text('search-job-state',e.message)}};$('enrich-selected').onclick=async()=>{try{const r=await request('api/discovery/enrich',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({listing_ids:[...chosen]})});if(r.id){job=r.id;localStorage.setItem('sector-job',job);$('cancel-search-job').disabled=false;if(timer)clearInterval(timer);timer=setInterval(poll,3000);poll()}else text('search-job-state',r.reason)}catch(e){text('search-job-state',e.message)}};$('evaluate-selected').onclick=()=>evaluate(false);$('evaluate-all').onclick=()=>evaluate(true);$('cancel-search-job').onclick=async()=>{if(job)await request('api/discovery/jobs/'+job+'/cancel',{method:'POST'})};$('catalog-refresh').onclick=async()=>{const market=$('sector-market').value;if(!market){text('search-state','갱신할 국가를 선택하세요.');return}try{await request('api/discovery/refresh?market='+market,{method:'POST'});text('search-state','목록 갱신 요청됨 · 수집 상태를 확인하세요.');health()}catch(e){text('search-state',e.message)}};
$('manager-refresh').onclick=async()=>{try{const r=await request('api/discovery/institution/sec13f?manager_cik='+encodeURIComponent($('manager-cik').value),{method:'POST'});text('search-job-state',r.note||r.status)}catch(e){text('search-job-state',e.message)}};
$('import-data').onclick=async()=>{try{const file=$('data-import').files[0];if(!file)throw Error('자료 파일을 선택하세요.');if(file.size>10000000)throw Error('자료 파일은 10MB 이하로 나누어 주세요.');const body=JSON.parse(await file.text()),path=body.kind?'api/discovery/flows/import':'api/discovery/import';await request(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});text('search-job-state','자료를 저장했습니다.');health();find()}catch(e){text('search-job-state',e.message)}};
health();find();setInterval(health,10000);job=localStorage.getItem('sector-job');if(job){timer=setInterval(poll,3000);poll()}
})();</script>'''
